#include <stdio.h>
int main(){
    int num;
    printf("\n\n\n Ingresa un numero:  ");
    scanf("%d", &num);
    if (num%2 == 0) /*AQUI EN ESTA PARTE EL PORCENTAJE SIGNIFICA EL RESIDUO DE UNA DIVISION QUE EN ESTE CASO TIENE QUE SER 0 Y ESO SIGNIFIQUE QUE ES PAR O IMPAR,
    EN ESTE CASO NO QUEREMOS LO NOS DA DE RESULTADO POR QUE 10/2 ES 5 Y TAMBIEN SERVIRIA PERO LO QUE ES IMPORTANTE
    ES DETERMINAR SI EL RESIDUO ES 0 YA QUE SI DIVIDES 10/2 PUES UN NUMERO MULTIPLICADO POR 2 QUE ME DE 10 ES 5 Y 
    5 POR 2 ES 10 PARA 10 ES 0 ENTONCES ES PAR, EN CAMBIO 5/2 NO HAY NUMERO QUE MULTIPLOCADO POR DOS ME DE 5 Y EL MAS CERCANO
    SERIA 2 Y 2 POR 2 ES 4 PARA 5 ES 1, ENTONCES ES IMPAR YA QUE SE NO DA A LA PRIMERA MUTIPLICACION 
    ESTE SIMBOLO DE PORCENTAJE JUNTO CON LOS DE SUMA, RESTA, DIVISION, ECT SE LLAMAN
    OPERADORES ARITMETICOS*/
    /* EL SIMBOLO DE DOBLE IGUAL == SE USAN EN ESTOS CASOS YA QUE ES COMO SI COMPARARAS EL NUMERO (VALOR) CON LA VARIABLE
    Y EL SIMBOLO DE SOLO UN IGUAL = SE USA PARA ASIGNAR VALORES A UN VARIABLE*/
    {
        printf("El numero es PAR  ");
    }
    else
    {
        printf("El numero es IMPAR  ");
    }
    
    



}